// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class ConsultationResponse
{
    public int ResponseId { get; set; }

    public int RequestId { get; set; }

    public int? DoctorId { get; set; }

    public string Response { get; set; }

    public string Attachments { get; set; }

    public bool IsFromUser { get; set; }

    public bool IsQuestion { get; set; }

    public bool? IsSystemMessage { get; set; }

    public int? ParentResponseId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User Doctor { get; set; }

    public virtual ICollection<ConsultationResponse> InverseParentResponse { get; set; } = new List<ConsultationResponse>();

    public virtual ConsultationResponse ParentResponse { get; set; }

    public virtual ConsultationRequest Request { get; set; }
}